# 运行： $ cargo +nightly fmt
#
# 配置文档：https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#control_brace_style
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
#
unstable_features = true

imports_indent = "Block"
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true

spaces_around_ranges = true
newline_style = "Native"

control_brace_style = "AlwaysSameLine"
fn_args_density = "Compressed"
format_macro_matchers = true

format_strings = true
